;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Class.Titan\\",NewTagName="Character.Class.Titan")
+GameplayTagRedirects=(OldTagName="Ability.Active.AirDash",NewTagName="Ability.Active.Dash")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Active",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Shockwave",DevComment="")
+GameplayTagList=(Tag="Ability.Active.TransformBig",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Transforming",DevComment="")
+GameplayTagList=(Tag="Ability.Active.TransformNormal",DevComment="")
+GameplayTagList=(Tag="Ability.Active.TransformSmall",DevComment="")
+GameplayTagList=(Tag="Character",DevComment="")
+GameplayTagList=(Tag="Character.Class",DevComment="")
+GameplayTagList=(Tag="Character.Class.Pixie",DevComment="")
+GameplayTagList=(Tag="Character.Class.Titan",DevComment="")
+GameplayTagList=(Tag="Character.Class.Versatile",DevComment="")
+GameplayTagList=(Tag="Cooldowns",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Shockwave",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Transform",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Damage.Type",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Heavy",DevComment="")
+GameplayTagList=(Tag="Damage.Type.Normal",DevComment="")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="Event.Landed",DevComment="")
+GameplayTagList=(Tag="Input",DevComment="")
+GameplayTagList=(Tag="Input.Ability",DevComment="")
+GameplayTagList=(Tag="Input.Ability.AirDash",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.TransformBig",DevComment="")
+GameplayTagList=(Tag="Input.Ability.TransformSmall",DevComment="")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Movement",DevComment="")
+GameplayTagList=(Tag="State.Movement.Flying",DevComment="")
+GameplayTagList=(Tag="State.Size",DevComment="")
+GameplayTagList=(Tag="State.Size.Big",DevComment="")
+GameplayTagList=(Tag="State.Size.Normal",DevComment="")
+GameplayTagList=(Tag="State.Size.Small",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")
+GameplayTagList=(Tag="Status.RegenBlocked",DevComment="")
+GameplayTagList=(Tag="Upgrade",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Base",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Base.Damage",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Base.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Base.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Big",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Big.Damage",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Big.Knockback",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Small",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Small.Airdash",DevComment="")
+GameplayTagList=(Tag="Upgrade.Skill.Small.StaminaFlight",DevComment="")

